language: cpp
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -qq libxi-dev; fi
script:
  - clang++ -v
  - cd src && ./externals.sh
  - ./gmake.sh
  - cd build && make
